### ISSUE TITLE
Should we drop rafl dependency?

### ISSUE THREAD

**Issue by oliviertassinari** [michaelrhodes/scroll#10]
We are using your great *scroll* package [on Material-UI side](https://github.com/mui-org/material-ui/blob/eb1ad7c2fa9f5cf12cccf6abd3f246a08dd3556d/packages/material-ui/package.json#L63). However, I'm having some concern about the size of this package (673 B gzipped).
I have noticed that [we can save 49.1%](https://bundlephobia.com/result?p=scroll@2.0.3) of the package size by removing the *ralf* dependency. I believe that the `requestAnimationFrame` API is [mainstream enough](https://caniuse.com/#feat=requestanimationframe) now to be used without a [ponyfill](https://github.com/sindresorhus/ponyfill).

What do you think?

**Comment by michaelrhodes** [comment]
Removed in 3.0.0
