### ISSUE TITLE
Cancel on click as well as scroll

### ISSUE THREAD

**Issue by girvo** [michaelrhodes/scroll#2]
Hey there, lovely little library.

I noticed there's a "cancel" method, but I can't seem to call it. I have bound a click handler to body and want to cancel the autoscroll when anything is clicked, how do I achieve that?

**Comment by michaelrhodes** [comment]
Hey, sorry for the super slow response! I’ve actually done a bit of refactoring and released 1.0.0 which sees the scroll functions returning user-callable cancel methods. I also pulled out the mousewheel auto-cancelling functionality (I think that’s actually outside the scope of this module), but if you look at the example in the readme, you should see that it’d be easy to re-introduce that and also add your own click-to-cancel behaviour.

**Comment by girvo** [comment]
You rock, cheers! I can kill my hacky fork now :)
