### ISSUE TITLE
Scroll does not seem to be working on firefox 47.0

### ISSUE THREAD

**Issue by vjryan** [michaelrhodes/scroll#5]
So i ran into an issue with firefox 47.0 scroll does not seem to be working nor is it throwing any errors.

**Comment by michaelrhodes** [comment]
Hm, the tests are actually passing for that version. Could you please provide some code that reproduces the issue?

**Comment by vjryan** [comment]
We just found the issue. 

Turns out the scroll plugin is affected by other dom elements that rendered post page load. Our ad space JS was causing issues specific to firefox and npm-scroll.

The document.write was happening after the render and in firefox it was not able to redraw the new window height. Something others should be aware of. Even their native scroll was not working (in firefox).

Ty though for your speedy reply!

**Comment by michaelrhodes** [comment]
Ah! No worries, glad you got it all sorted out :)
