### ISSUE TITLE
Callback fires before scroll finished when scroll down

### ISSUE THREAD

**Issue by inferusvv** [michaelrhodes/scroll#6]
Hello. I found an issue with next code:

```
var scrollEl = document.querySelector('.scroll');
var btnEl = document.querySelector('.btn');

btnEl.addEventListener('click', function() {
	scroll('scrollTop', scrollEl, 100, {}, function() {
		console.log('DONE');
	});
});

scrollEl.addEventListener('scroll', function() {
	console.log('onScroll');
});
```

Here is JSFiddle: https://jsfiddle.net/buz5uxgh/1/

`scroll` event listener will be fired after container was scrolled and callback run.

Steps:

1. Click on `btnEl` (Scroll)
2. Check console logs

![2017-09-15 12 27 04](https://user-images.githubusercontent.com/3227120/30476001-501f6f00-9a11-11e7-9b04-80a8191c8a07.png)

**Comment by michaelrhodes** [comment]
Thanks for reporting this, it’s fixed as of 2.0.1 :)
