### ISSUE TITLE
A duration of 0 ms results in an animation

### ISSUE THREAD

**Issue by alexanderwallin** [michaelrhodes/scroll#7]
Passing `{ duration: 0 }` results in an animation, whilst `{ duration: 1 }` is pretty much instant. I'm building a React component that has a dynamic scroll duration prop, which now breaks. I've solved it by passing `1` when it is `0`, but it would be neater make everything transparent!

Cheers for a good lib.

**Comment by fiskus** [comment]
Same need. Created pull request for that #8

**Comment by michaelrhodes** [comment]
Hey gang, I just published version 2.0.2 which includes a patch for this issue. Sorry for the delay :)
